### ISSUE TITLE
Rounded Dash to Dock

### ISSUE THREAD

**Issue by perin-lionshead** [vinceliuice/WhiteSur-gtk-theme#1]
Hi,

I love this theme so much! Thank you! I am wondering how you are getting your dash to dock to round its bottom corners up in the screenshots?

Thank you so much!

**Comment by laichiaheng** [comment]
I think that they are using the Plank with WhiteSur theme, but it interact less with Gnome, so I still prefer Dash to Dock.

**Comment by vinceliuice** [comment]
I tried, but Dash to Dock does not support this,

**Comment by laichiaheng** [comment]
> I tried, but Dash to Dock does not support this,

You need to install Plank.

**Comment by zeparu** [comment]
im experimenting right now, and it seems like you can actually do something with dash to dock, but i dont know how reliable that is right now

i can get a "floating" look, but adding `margin-bottom: 10px !important` to `#dashtodockContainer #dash`, the !important will apply the margin in the overview too.

for rouding the bottom corners, i see very weird behaviour, because if you customize the "built-in theme" for dash-to-dock, with the class `.dashtodock`, you can get rounded corners no problem, but if you dont use that, you cannot get rounded corners on all sides

so bottom-rounded corners only work in the built-in theme somehow

- so what i do is i add the `margin-bottom: 10px !important` to the shell-theme
- in the folder of the dash-to-dock extension there is a stylesheet.css, in there i disable styling for `.dashtodock`
- i also disable the border:1px there that appears in smaller dock mode

and it will work, if you enable the built-in theme in the dash-to-dock extension

you will also see, that if you toggle between the built-in theme and disabling it, the only that that will change is the bottom corner rounding up

question is, how feasible this is to change or maybe automate for installation 

![grafik](https://user-images.githubusercontent.com/21054889/89134196-5da6b700-d523-11ea-8a9a-99755f06d2b9.png)
screenshot with built-in theme

![grafik](https://user-images.githubusercontent.com/21054889/89134204-67c8b580-d523-11ea-9cc3-6c30c1a9d763.png)
screenshot with built-in theme disabled

**Comment by vinceliuice** [comment]
@zeparu Well that's great! I think I can upload the `stylesheet.css` for people to download, and tell them how to use on the README

**Comment by laichiaheng** [comment]
@zeparu I still don't understand how you do it.

**Comment by zeparu** [comment]
[stylesheet.txt](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/5030556/stylesheet.txt)
@laichiaheng replace .local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css with the file i linked at the top (change the .txt to .css)

![grafik](https://user-images.githubusercontent.com/21054889/89452477-017ba700-d75e-11ea-9912-63b8fbb75c5c.png)
enable the built-in theme

**Comment by Yago-Maia** [comment]
When I do that, I lose transparency. What do I do?
![image](https://user-images.githubusercontent.com/9813972/97747766-3a13ee00-1acb-11eb-8921-2aeed48d9a46.png)

**Comment by vinceliuice** [comment]
Fixed

**Comment by 73** [comment]
@vinceliuice how is this fixed? Is there a new version?
