### ISSUE TITLE
Sonoma theme 

### ISSUE THREAD

**Issue by joaopdsilvadias** [vinceliuice/WhiteSur-gtk-theme#1005]
Could you tell me when you plan to make a new Sonoma theme for Gnome?

**Comment by vinceliuice** [comment]
Are there any changes to the new system theme?

**Comment by kernelb00t** [comment]
I think there are ones but for KDE made by @vinceliuice. Today, I think he is very busy and don't have time and/or will to put so much effort. I highly suggest you, if you have a little bit of time to spend, to help the project and contribute to it.

**Comment by michaelerule** [comment]
The only difference with Sonoma I've noticed so far is that the dark theme in Sonoma uses a brighter highlight on the window borders. It seems to also blend/interact the window decorations with the surrounding colour content in a more complicated way, but this would not be possible. 

I've tweaked WhiteSur-gtk-theme dark mode, standard definition, so that the xfwm4 window decorations look a bit more Sonoma like. 

You can get most of the way there by heading to WhiteSur-gtk-theme/src/assets/xfwm4/assets-Dark and changing the light highlight to #6f6f6f, dark border to #010101. I did a little bit more than this by taking screenshots of the actual Sonoma window borders, but nothing that would be appropriate for a pull request (only modified standard definition dark theme in xfwm4). 

Does anyone know how the window stiles for Firefox (and gnome shell, I believe), are defined in this theme? I can't seem to find any bitmaps that correspond to them, so I gather they are CSS or described some other way. I'd like to see if I can get the changes to the window borders more uniformly across applications.
