### ISSUE TITLE
UI glitch on the Firefox tabs

### ISSUE THREAD

**Issue by dhra** [vinceliuice/WhiteSur-gtk-theme#1026]
**Data:**
```
OS: Ubuntu 23.10
Desktop Env: Gnome 45
```
Commit ID: [fe10a62](https://github.com/vinceliuice/WhiteSur-gtk-theme/commit/fe10a629bb2e9ce71bea275da97acfbae55c0ef1)

**Steps to reproduce:**

- Install Firefox template using `./tweaks.sh -f alt`
- Set `browser.tabs.firefox-view-next` to `true` from `about:config`
- You should open tabs in **full screen** mode
- Pin 6 tab on the browser.
- Open more than 30 new tabs

[Screencast from 2024-02-21 08-13-28.webm](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/29132485/baa34449-86e5-41c4-88ae-7010542b09f2)

**Comment by stoneC0der** [comment]
@dhra I am unable to reproduce the bug although I am aware of it when using the Monterey theme for Firefox, but the alt variant works just fine.
The Monterey bug happens when the mostly when Firefox is not in full screen.

I just opened more than 30 tabs with 8 being pined, the extra scroll horizontally nicely, which the reason why I switch to Alt variant from Monterey.

**Comment by dhra** [comment]
@stoneC0der It exclusively occurs in full-screen mode

**Comment by dhra** [comment]
@kernelb00t

Native Resolution 2560 x 1440
Aspect Ratio 16:9
