### ISSUE TITLE
ERROR: Firefox is running, please close it

### ISSUE THREAD

**Issue by saaditory** [vinceliuice/WhiteSur-gtk-theme#181]
Firefox option is displaying this error message even though it's closed. Tried to run immediately after login but still gives this error. Even tried to reinstall.

![image](https://user-images.githubusercontent.com/38633812/114285565-a5e28580-9a71-11eb-8d5e-7da49beb5c77.png)

**Comment by vinceliuice** [comment]
Don't mix use --firefox and --edit-firefox!, just use --firefox or --edit-firefox

**Comment by rivanfebrian123** [comment]
> Don't mix use --firefox and --edit-firefox!, just use --firefox or --edit-firefox

Using both --firefox and --edit-firefox shouldn't be a problem. The problem is `elif pgrep -x "firefox" &> /dev/null || pgrep -f "firefox" &> /dev/null; then` in `tweaks.sh`. If we just use `elif pgrep -x "firefox" &> /dev/null; then` it only works on some distros, but if we add `... || pgrep -f "firefox" &> /dev/null` it causes this problem. You have a better solution for detecting running app?

**Comment by rivanfebrian123** [comment]
I added `... || pgrep -f "firefox" &> /dev/null` because Firefox process detection doesn't work if we use only  `pgrep -x "firefox" &> /dev/null` on Fedora XFCE. Adding `... || pgrep -f "firefox" &> /dev/null` is problematic too since it'll also detect every command contains `... firefox ...` as `firefox` including our installer (for example `tweaks.sh --firefox`). I think using `elif pidof "firefox" &> /dev/null; then` will solve this problem and works on every popular distros. I didn't test on other distros, anyway

**Comment by vinceliuice** [comment]
I have fedora and manjaro, I'll test this on my distros anyway!

**Comment by saaditory** [comment]
Still inconsistent and misleading. (062b643 - Fixed #181)

![image](https://user-images.githubusercontent.com/38633812/114298529-436ca200-9ad0-11eb-83e0-dfd3019e4243.png)

**Comment by saaditory** [comment]
Still problematic..

![image](https://user-images.githubusercontent.com/38633812/114298730-30a69d00-9ad1-11eb-9b71-80d033a53523.png)

**Comment by saaditory** [comment]
Still problematic after 062b643

![image](https://user-images.githubusercontent.com/38633812/114298778-706d8480-9ad1-11eb-853e-3c35d6fed6b8.png)

**Comment by rivanfebrian123** [comment]
> Still problematic after [062b643](https://github.com/vinceliuice/WhiteSur-gtk-theme/commit/062b643627e6f42f10aa9b7607eabb2855f0d9a4)
> 
> ![image](https://user-images.githubusercontent.com/38633812/114298778-706d8480-9ad1-11eb-853e-3c35d6fed6b8.png)

Yeah, cuz it's not implemented yet :D

**Comment by vinceliuice** [comment]
I'll test this!

**Comment by rivanfebrian123** [comment]
Vince, I already tested it and found that `pidof` works better than `pgrep`

**Comment by vinceliuice** [comment]
No problem! thanks you fix this!

**Comment by rivanfebrian123** [comment]
Youre welcome :)

**Comment by rivanfebrian123** [comment]
Vince, I'm sorry. You forgot to replace `elif pgrep -x "firefox" &> /dev/null || pgrep -f "firefox" &> /dev/null; then` with `elif pidof "firefox" &> /dev/null; then` in `tweaks.sh`

**Comment by vinceliuice** [comment]
Now it's OK!
