### ISSUE TITLE
Nautilus, left column not increase at text length

### ISSUE THREAD

**Issue by luisrdzruiz** [vinceliuice/WhiteSur-gtk-theme#23]
In nautilus, left column is small, and my google account overlap.
I can't resize.
![image](https://user-images.githubusercontent.com/43277999/88686156-6a0eb800-d0bc-11ea-911b-fd96e8b709e1.png)

another thing, when pass the mouse hover, the background of items not refresh.

Best Regards

**Comment by vinceliuice** [comment]
Solid version has fixed this issue

**Comment by jindradev** [comment]
2020-08-27 from gnome-looks, not fixed. Caused by menu item overflowing menu - menu's fault as shown on screenshots - not expanding correctly (correct wrapper)
![Screenshot from 2020-08-31 00-04-47](https://user-images.githubusercontent.com/32195723/91670475-36410b00-eb1e-11ea-9b73-a0d24be69565.png)
![Screenshot from 2020-08-31 00-05-17](https://user-images.githubusercontent.com/32195723/91670476-36d9a180-eb1e-11ea-9d3f-2dea6f182491.png)
