### ISSUE TITLE
Oops... there's nothing to tweaks...

### ISSUE THREAD

**Issue by gitAlwin** [vinceliuice/WhiteSur-gtk-theme#287]
A number of tweaks don't work for me. For instance if I want to change the 'Activities'  icon I get a message that there is nothing to tweak:
```
./tweaks.sh -i ubuntu

  Oops... there's nothing to tweaks...
```
However, the apple logo is still there (instead of the Ubuntu one), also after restarting gnome or rebooting the computer altogether.

When trying to change the logo using the `install` script also doesn't work.

Any idea what can be causing this? I'm running Ubuntu 20.04 Gnome 3.36.

Thanks in advance!

**Comment by vinceliuice** [comment]
It's install.sh not tweaks.sh

**Comment by gitAlwin** [comment]
Thank you for the reply, unfortunately using the ```install.sh``` script also doesn't work.

**Comment by rivanfebrian123** [comment]
Well, GNOME actually has 2 different components. It has GNOME Shell and GDM (the login manager). So that's why we have 2 different options to install the shell theme. First, you can run `sudo ./tweaks.sh -g -r` to install the **GDM** theme. Or, you can install the **shell theme only** by running `./install.sh`

**Comment by baleboy** [comment]
In case someone else stumbles on this, the way to change the activity icon (at least for me) is `sudo ./tweaks.sh -g -i ubuntu`
