### ISSUE TITLE
Silent installation

### ISSUE THREAD

**Issue by steven-hh-ding** [vinceliuice/WhiteSur-gtk-theme#304]
Hi! Thanks for the great work!! We really love it and integrate this theme to our kubenetes cluster pods to provide themed user interface. We used to run the old installer in our automated pipeline so the installation can be automated. However the new installer always require interaction (prompts). Would it be possible to run it silently (maybe we have missed certain CLI option).. Thanks

**Comment by rivanfebrian123** [comment]
Your welcome!

In the current version, it's actually possible to avoid the prompt by running `./install.sh` or `./tweaks.sh` with `sudo`, and make sure your arguments is just correct, otherwise, it will prompt an interactive dialog or something. But, in my PR, it has some prompts on some cases like when you use Clear Linux but you have `dnf` installed, it will ask you like "Using DNF in Clear Linux is dangerous. It may break your system. You wanna remove that?"

BTW, thanks for your early reporting. It's gonna help the other distro packager like you to package this theme without having to patch so many things

**Comment by rivanfebrian123** [comment]
Silent mode is here: #296! Let's try it

**Comment by steven-hh-ding** [comment]
omg that's quick! Thanks a lot! we were just trying out setting sudo in docker file. Let me update the pipeline to pull from master. 🔥

**Comment by rivanfebrian123** [comment]
Your welcome :)

> we were just trying out setting sudo in docker file

`install.sh` and `tweaks.sh` doesn't accept stdin pipe, so you can easily pass a password from `echo` to `sudo`, for example: `echo <password> | sudo -S ./install.sh`
