### ISSUE TITLE
Unable to install the theme due to error.

### ISSUE THREAD

**Issue by JJorbann** [vinceliuice/WhiteSur-gtk-theme#356]
=========== ERROR LOG ===========
  >>> E: The repository 'cdrom://Ubuntu-Budgie 21.04 _Hirsute Hippo_ - Release amd64 (20210420) hirsute Release' does not have a Release file.
  >>> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
  >>> N: See apt-secure(8) manpage for repository creation and user configuration details.
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh at 130;136
  SNIPPET:
    >>> apt update -y
  TRACE  :
    >>> signal_error
    >>> prepare_install_apt_packages
    >>> install_theme_deps
    >>> install_themes
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu;debian;21.04
  SUDO   : no
  GNOME  : none
  REPO   : 2021-07-06T10:08:38-0500

![image](https://user-images.githubusercontent.com/87100342/124838557-b6a97700-df4c-11eb-97c3-3aee7762c78a.png)

**Comment by JJorbann** [comment]
I am completely new with the likes of Linux, and have no idea what any of this means.
If I could get some assistance, that would be wonderful!

**Comment by vinceliuice** [comment]
Disable this cdrom://Ubuntu-Budgie from your source list

**Comment by rivanfebrian123** [comment]
- https://itsfoss.com/repository-does-not-have-release-file-error-ubuntu/
- https://askubuntu.com/questions/866901/what-can-i-do-if-a-repository-ppa-does-not-have-a-release-file

@vinceliuice I think we need to write an FAQ and give a hint on the installer about this

**Comment by vinceliuice** [comment]
You are right, Many Ubuntu users can’t handle these issues，It would be great if github had an automatic response function based on keywords.

**Comment by vinceliuice** [comment]
@rivanfebrian123 can we use `apt upgrade` instand of `apt update -y`, Because these useless repositories do not affect the normal upgrade of the ubuntu system!

**Comment by rivanfebrian123** [comment]
> You are right, that would be helpful, Many Ubuntu users can’t handle these issues，It would be great if github had an automatic response function based on keywords. @rivanfebrian123

Yeah, I found this Github action tho: https://github.com/marketplace/actions/issue-matching-auto-closer



> @rivanfebrian123 can we use `apt upgrade` instand of `apt update -y`? Because these useless repositories do not affect the normal upgrade of the ubuntu system!

Usually on the first time use of Ubuntu installation, you can't install some non essential packages like `sassc`. So, you need to update your repo. Check this out: https://itsfoss.com/unable-to-locate-package-error-ubuntu/

Upgrading point-release distro packages isn't required to make sure dependencies don't break the system because the maintainers guarantee that the package versions are compatible to each other unlike rolling-release distros. Check: https://forum.manjaro.org/t/glib2-v2-66-breaks-cifs-operation-in-filemanager/29457/2. On my case, on Manjaro XFCE, I can't open my settings after upgrading the glib2 package

**Comment by vinceliuice** [comment]
I get this, then we can try this Github action

**Comment by rivanfebrian123** [comment]
Sure!

**Comment by vinceliuice** [comment]
How to make the installer complete normally and then report this error instead of stopping the installation, because this kind of problem does not affect the installation of sassc and other dependencies on ubuntu. I tested on my ubuntu and the sassc (or other dependencies) have been installed successfully , But because of these error reports, the installation program is terminated, but these third-party repository errors do not affect the normal installation of these dependencies!

**Comment by rivanfebrian123** [comment]
I didn't test it yet, but you can try:

- [x] replace all `sudo apt update -y` with `sudo apt update --allow-unauthenticated -y`

And well, could you please try that on some newly installed Ubuntu distros? I still have lots of college assignments :D

**Comment by vinceliuice** [comment]
👌I'll try it

**Comment by rivanfebrian123** [comment]
Don't forget to add some invalid repo/PPAs and try again (on different distros)

**Comment by vinceliuice** [comment]
No problem!

**Comment by JJorbann** [comment]
I went about solving the issue by installing a more known fork of Ubuntu.

After reinstalling the OS, it worked on he first try.
Sorry about that,
I figured it was something that I was doing wrong, but I guess it was just the fork of Ubuntu that I was using.

**Comment by fossfreedom** [comment]
@JJorbann I note the "ubuntu budgie" reference here - can I ask what is the fork of UB you are referring to here?
