### ISSUE TITLE
Problem with connecting to flatpak

### ISSUE THREAD

**Issue by Nakamerica** [vinceliuice/WhiteSur-gtk-theme#551]
Oops! Operation failed...

  =========== ERROR LOG ===========
  
>>>>>>> No error log found <<<<<<
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> lib-core.sh
    >>> lib-flatpak.sh at 51
    >>> lib-install.sh
    >>> tweaks.sh
  SNIPPET:
    >>> cp -a "$theme_path/gtk-3.0/"* "$build_dir/files"
  TRACE  :
    >>> signal_error
    >>> pakitheme_gtk3
    >>> connect_flatpak
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : ubuntu debian;pop;20.04
  SUDO   : no
  GNOME  : old
  REPO   : 2022-02-06T08:33:52+0530

Hi, I'm trying to connect the whitesur-gtk-theme to my flatpak applications, however the above issue comes up when I enter the command. A screenshot is attached. 

![image](https://user-images.githubusercontent.com/88226614/152779577-734f0f1d-1972-45d7-9b0e-3166b167d952.png)

Thanks for any help offered.

**Comment by shans10** [comment]
I was also unable to connect the flatpak theme at first with just `./tweaks.sh -F` then I used `./tweaks.sh -F -c dark` since I installed only the dark variant but then it gave the same error as you finally when I included `--theme -t` parameter as well that it actually worked for me, so what finally worked was `./tweaks.sh -F -c dark -t blue`. It seems that we need to include these two parameters appropriately as used while installing the theme itself in order for it to work succesfully.

**Comment by Nakamerica** [comment]
Thanks, although now i use stylepak for compatibility with flatpak apps.
