### ISSUE TITLE
Can't install anymore

### ISSUE THREAD

**Issue by dragonattheend** [vinceliuice/WhiteSur-gtk-theme#666]
Oops! Operation failed...

  =========== ERROR LOG ===========
  >>> Internal Error: File to read not found or unreadable:WhiteSur-gtk-theme-master/src/main/gtk-4.0/gtk-.scss
  
  =========== ERROR INFO ==========
  FOUND  :
    >>> install.sh
    >>> lib-core.sh
    >>> lib-install.sh
  SNIPPET:
    >>> sassc ${SASSC_OPT} "${THEME_SRC_DIR}/main/gtk-4.0/gtk${color}.scss" "${TARGET_DIR}/gtk.css"
  TRACE  :
    >>> signal_error
    >>> config_gtk4
    >>> install_libadwaita
    >>> main
  
  =========== SYSTEM INFO =========
  DISTRO : workstation;platform:f36;fedora;36
  SUDO   : no
  GNOME  : 42-0

**Comment by C4pt4inM** [comment]
Having same error so not duplicating.
command I ran
```
 ./install.sh -o normal -c Dark -t all -p 30 -P smaller -i fedora --libadwaita -N glassy

```
![image](https://user-images.githubusercontent.com/26740729/186538620-5e69d4f0-f968-4dca-b367-d3552f30c676.png)

**Comment by Irevirt** [comment]
Had the same error on openSUSE Tumbleweed. But I might have found a temporary workaround.

In the last update to lib-install.sh, line 539 was changed from


`config_gtk4 "${colors[0]}" "${alt[0]}"` 

to 

`config_gtk4 "${colors[1]}" "${alt[0]}"`


Changing it back to `config_gtk4 "${colors[0]}" "${alt[0]}` "fixed" the issue to me, but I wouldn't call this an actual "fix", because I have no programming knowledge and I'm not smart enough to fully understand how the installation work, but if the value was changed from 0 to 1, there has to be a reason that I'm not understanding. Right now though everything seems to be working fine.

To install the theme, I used
`./install.sh -o normal -c Dark -t blue -i opensuse -N glassy --normal -l`

**Comment by vinceliuice** [comment]
Fixed!
