### ISSUE TITLE
I can't reset the libadwaita theme after removing.

### ISSUE THREAD

**Issue by svta-7125** [vinceliuice/WhiteSur-gtk-theme#902]
Fedora 38
I installed WhiteSur with ./install.sh -c Dark -i fedora -l --darker with libadwaita. After I didn't like the libadwaita change, I went ahead and removed it. However the libadwaita theme remained and I couldn't change it back. A little help?
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/117646988/90cdf5be-c480-4c16-a897-379cf42a16b3)

**Comment by vinceliuice** [comment]
Run `./intall.sh -l -r` to remove it

**Comment by svta-7125** [comment]
Thank you for replying. The installer successfully removed the gtk 4 theme, but nautilus and gnome-software didn't change themes after several restarts.

**Comment by vinceliuice** [comment]
Gnome  do not support theme switch anymore

**Comment by svta-7125** [comment]
I don't understand.

**Comment by vinceliuice** [comment]
Since Gnome > 42 it use libadwaita as app ui. and not support custom themes anymore, that means you can not use gnome-tweaks to change your theme in last Gnome

**Comment by vinceliuice** [comment]
This is the info on Readme:
Since the release of Gnome 43.0, more and more built-in apps use libadwaita now, and libadwaita does not support custom themes, which means we cannot change the appearance of app using libadwaita through gnome-tweaks or dconf-editor. For users who love custom themes, it’s really sucks!

Anyway if anybody who still want to custom themes we can only do this way:

that is to use the theme file to overwrite the gtk-4.0 configuration file. The result is that only Fixed making all gtk4 apps use one theme and cannot be switched (even can not switch to dark mode) If you want to change a theme, you can only re-overwrite the gtk-4.0 configuration file with a new theme, I know this method is not perfect, But at the moment it is only possible to continue using themes for libadwaita's apps ...

**Comment by phamson02** [comment]
@vinceliuice you may misunderstand the issue here. Changes made by your script retain in nautilus and gnome-software despite having ran the remove command `./intall.sh -l -r` as instructed. I am facing the same issue here.

**Comment by vinceliuice** [comment]
Are not the nautilus and gnome software using default libadwaita theme now ！

**Comment by phamson02** [comment]
I have been able to reset the libadwaita theme by deleting the ~\.config\gtk-4.0 folder. Maybe there are some issues within your reset script?

**Comment by vinceliuice** [comment]
Fixed now
